### ISSUE TITLE
重新调整社区文档顺序

### ISSUE THREAD

**Issue by I-love-study** [GraiaCommunity/Docs#14]
1. 将 Saya 调前，将其放置在仅次于hello world的位置，以便用户能够一开始能够在使用社区已有代码的同时，写出自己的一些小功能
2. 前面重点介绍 "How" 而不是 "Why"，将实现放在最前面，而原理之类的放在最后面
3. 将关于 Saya 的部分 Behavior / Schema (e.g: Console / Scheduler) 下放到那些模块所属的文章
4. 提供一个相当简易的Saya运行环境（如 [GraiaCommunity/github-bot](https://github.com/GraiaCommunity/github-bot)），并且打包成 zip 供新手用户下载（zip就放在 [GraiaCommunity/EroEroBot](https://github.com/GraiaCommunity/EroEroBot) 中就好）
5.

**Comment by Redlnn** [comment]
要不要把文章的源文件名去掉数字，使用章节内容主题或主要内容作为标题
