### ISSUE TITLE
文档里的小问题

### ISSUE THREAD

**Issue by ZhaoZuohong** [GraiaCommunity/Docs#17]
在[3. 你可能会遇到的一些奇奇怪怪的小问题](https://graiax.cn/make_ero_bot/before/3_small_question.html#_3-%E4%BD%A0%E5%8F%AF%E8%83%BD%E4%BC%9A%E9%81%87%E5%88%B0%E7%9A%84%E4%B8%80%E4%BA%9B%E5%A5%87%E5%A5%87%E6%80%AA%E6%80%AA%E7%9A%84%E5%B0%8F%E9%97%AE%E9%A2%98)一节的开头，有这样一段：

```
::: tsokkomi 某些问题，可能跟 GraiaProject 的库没有任何关系， 仅仅是因为你有可能会在机器人上遇到才写上去的 :::
[#](https://graiax.cn/make_ero_bot/before/3_small_question.html#graia-%E7%9B%B8%E5%85%B3)
```

是不是写错了？

**Comment by Redlnn** [comment]
fixed in fd26f67
