### ISSUE TITLE
边栏的引言链接是404

### ISSUE THREAD

**Issue by ZhaoZuohong** [GraiaCommunity/Docs#18]
边栏的[引言](https://graiax.cn/make_ero_bot/README.md)链接是404。

**Comment by Redlnn** [comment]
属于 VuePress 的问题，无法修复

**Comment by I-love-study** [comment]
> 属于 VuePress 的问题，无法修复

<img width="147" alt="image" src="https://user-images.githubusercontent.com/39652142/160229223-99870bc8-8be5-4e9e-821e-e68335dd807b.png">
这样就行了来着
