### ISSUE TITLE
Twilight一导入就报错 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by bakaEC** [GraiaCommunity/Docs#20]
![图片](https://user-images.githubusercontent.com/55977904/161022827-b4eede9a-6b80-4d9c-8ea2-dc48e8a1c94a.png)

怎么会事呢owo

**Comment by Redlnn** [comment]
请问一下 Ariadne 的版本？

**Comment by bakaEC** [comment]
graia-ariadne        0.6.13
graia-broadcast      0.16.1
graia-saya           0.0.15
graia-scheduler      0.0.6
graiax-silkcoder     0.2.0

**Comment by Redlnn** [comment]
可能是 Ariadne 的问题，看看 @BlueGlassBlock 怎么说

**Comment by BlueGlassBlock** [comment]
Ariadne `0.6.14` 已经修复了
