### ISSUE TITLE
Awesome Graia

### ISSUE THREAD

**Issue by Redlnn** [GraiaCommunity/Docs#30]
此处收集使用 Graia 系列包的 Bot 或其他项目，其中大部分都不 Awesome，偶尔更新，如需要添加请发评论。

> 除框架外按作者及项目名字母排序

## 框架/工具

- [Avilla](https://github.com/GraiaProject/Avilla) - 又名 v5
- [Ariadne](https://github.com/GraiaProject/Ariadne) - 又名 v4p/v4+/v5-
- [Application](https://github.com/GraiaProject/Application) - 又名 v4，已停更且停止支持
- [Kuriyama](https://github.com/Lxns-Network/mirai-python-sdk) - 又名 v3，其实不属于 Graia，已停更且停止支持
- [Broadcast Control](https://github.com/GraiaProject/BroadcastControl) - 事件（广播）系统 —— Graia 的基石
- [Saya](https://github.com/GraiaProject/Saya) - 模块加载器（用于将不同的功能模块化）
- [Scheduler](https://github.com/GraiaProject/Scheduler) - 定时（计划）任务执行器
- [Amnesia](https://github.com/GraiaProject/Amnesia) - v4p & v5 共用组件集合（供内部使用）
- [Status API](https://github.com/GraiaProject/statv) - 内部使用的底层 API
- [Launart - Launch for Graia Project](https://github.com/GraiaProject/launart) - 内部使用的统一的应用实例启动时部件管理

### 使用 Ariadne 的项目

- [AwordaProject/Aworda-LBot](https://github.com/AwordaProject/Aworda-LBot)
- [beibao233/Teacher-Nakamura](https://github.com/beibao233/Teacher-Nakamura)
- [BlueGlassBlock/Xenon](https://github.com/BlueGlassBlock/Xenon)
- [djkcyl/ABot-Graia](https://github.com/djkcyl/ABot-Graia) - 已停更
- [djkcyl/BBot-Graia](https://github.com/djkcyl/BBot-Graia)
- [I-love-study/A_Simple_QQ_Bot](https://github.com/I-love-study/A_Simple_QQ_Bot)
- [LycmSky/Qbot](https://github.com/LycmSky/Qbot) - 存在语法错误（bug）
- [MadokaProject/Madoka](https://github.com/MadokaProject/Madoka)
- [nullqwertyuiop/Chitung-python](https://github.com/nullqwertyuiop/Chitung-python)
- [ProjectNu11/Project-Null](https://github.com/ProjectNu11/Project-Null) - [插件仓库](https://github.com/ProjectNu11/PN-Plugins)
- [Redlnn/redbot](https://github.com/Redlnn/redbot)
- [RF-Tar-Railt/RaianBot](https://github.com/RF-Tar-Railt/RaianBot)
- [SAGIRI-kawaii/sagiri-bot](https://github.com/SAGIRI-kawaii/sagiri-bot)
- [YUASDS/Yubot](https://github.com/YUASDS/Yubot) - 部分 cv ABot
- [zzzzz167/Yuki](https://github.com/zzzzz167/Yuki)

### 使用 Avilla 的项目

- [Little-LinNian/linnian-qwq-bot](https://github.com/Little-LinNian/linnian-qwq-bot) - 已停更

### 比较难看懂（魔法比较多）的项目

- [luxuncang/Alice](https://github.com/luxuncang/Alice)

### 使用已失去支持的 Application 但仍有参考价值的项目

- [purofle/Black-Cat-qqbot](https://github.com/purofle/Black-Cat-qqbot)
- [SiriusNEO/Touhou-QQBot](https://github.com/SiriusNEO/Touhou-QQBot)
- [luxuncang/Bot_momo](https://github.com/luxuncang/Bot_momo)

### 不是一个 Bot

- [CubeSugarCheese/WapQQ](https://github.com/CubeSugarCheese/WapQQ)

### Saya 模块

> 由于以下或其他未提及的原因而不推荐参考：
> - 未完成
> - 质量不高
> - 安全原因
> - 长期未更新/使用不受支持的框架

- [dxzenghan/graiax-sayamod-record](https://github.com/dxzenghan/graiax-sayamod-record) - 基于 Application
- [EricTianC/graiax-sayamod-requireEz](https://github.com/EricTianC/graiax-sayamod-requireEz) - 基于 Application
- [EricTianC/graiax-sayamod-nbnhhsh](https://github.com/EricTianC/graiax-sayamod-nbnhhsh) - 基于 Application
- [SAGIRI-kawaii/saya_plugins_collection](https://github.com/SAGIRI-kawaii/saya_plugins_collection) - 基于 Application

### Other

> 由于以下或其他未提及的原因而不推荐参考：
> - 未完成/功能较少
> - 缺失 README
> - 代码/项目质量不高
> - 目录结构混乱
> - 安全原因
> - 长期未更新/使用不受支持的框架

- [384606266/QQ-bot](https://github.com/384606266/QQ-bot)
- [amtoaer/github-notifier-bot](https://github.com/amtoaer/github-notifier-bot)
- [Crepuscule-v/QQbot](https://github.com/Crepuscule-v/QQbot)
- [GWDx/Mado](https://github.com/GWDx/Mado)
- [FantasticGu/-graia-application-QQ-](https://github.com/FantasticGu/-graia-application-QQ-) - 已停更
- [ieew/miraibot](https://github.com/ieew/miraibot) - ???（魔女血压拉满）
- [JINO93/AriadneBot](https://github.com/JINO93/AriadneBot)
- [Little-LinNian/DeadGhost](https://github.com/Little-LinNian/DeadGhost)
- [LittleSkinCommspt/approval-bot](https://github.com/LittleSkinCommspt/approval-bot)
- [weifanxiang/qq-bot](https://github.com/weifanxiang/qq-bot)
- [Reilkay/weather-bot](https://github.com/Reilkay/weather-bot)
- [SAGIRI-kawaii/QQBot](https://github.com/SAGIRI-kawaii/QQBot) - 基于 Kuriyama
- [SAGIRI-kawaii/SagiriGraiaPlatform](https://github.com/SAGIRI-kawaii/SagiriGraiaPlatform) - ???（魔女血压拉满）
- [SuperWaterGod/BFserver-Bot](https://github.com/SuperWaterGod/BFserver-Bot)
- [thx114/fthx-bot](https://github.com/thx114/fthx-bot)
- [xlxyzzgzs/a-qqbot-based-graia](https://github.com/xlxyzzgzs/a-qqbot-based-graia)
- [xuanweiace/DailyQQBot](https://github.com/xuanweiace/DailyQQBot)
- [yeren66/QQBot](https://github.com/yeren66/QQBot)
- [YYJJCCD/quncloud](https://github.com/YYJJCCD/quncloud)
- [ZXCVBNNGG/githubot](https://github.com/ZXCVBNNGG/githubot)
- [ZXCVBNNGG/setu](https://github.com/ZXCVBNNGG/setu)
- [ZXCVBNNGG/Tsukiko](https://github.com/ZXCVBNNGG/Tsukiko)

## 友情链接（bushi）

- [YiriMiraiProject/YiriMirai](https://github.com/YiriMiraiProject/YiriMirai) - 也是一个 Python QQ Bot 框架

**Comment by BlueGlassBlock** [comment]
Is `Awesome Graia` **really** awesome?
