### ISSUE TITLE
压缩包加密教程

### ISSUE THREAD

**Issue by RainyNian** [GraiaCommunity/Docs#32]
@nullqwertyuiop 交给 null 来
![Screenshot_2022-07-09-12-09-57-007_com tencent mobileqq](https://user-images.githubusercontent.com/65386393/178091085-4bfb11ec-fc26-431b-b0ec-da53e2e22b3c.jpg)

**Comment by nullqwertyuiop** [comment]
？

晚点再写<del>，先摸点鱼</del>

**Comment by Redlnn** [comment]
> ？
> 
> 晚点再写~，先摸点鱼~

催更

**Comment by RainyNian** [comment]
催更

**Comment by nullqwertyuiop** [comment]
霖念帮我写
-------- Original message --------From: 霖念 ***@***.***> Date: 7/20/22  12:43  (GMT+08:00) To: GraiaCommunity/Docs ***@***.***> Cc: Null ***@***.***>, Mention ***@***.***> Subject: Re: [GraiaCommunity/Docs] 压缩包加密教程 (Issue #32) 

催更

**Comment by BlueGlassBlock** [comment]
No.
