### ISSUE TITLE
更新至 0.10.0

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaCommunity/Docs#63]
建议检查下消息处理器那章

**Comment by Redlnn** [comment]
最好还是remake，但是写不动

**Comment by Redlnn** [comment]
## 0.7.16 ~ 0.10.1 中可能需要涉及的更改汇总：

-  `AnnotationWaiter`
- 移除了 `as_display` 等弃用方法
- `BotMessage` 被标记为弃用
- Image 和 FlashImage 的新增元信息字段
- `get_bot_list` 用于获取所有登录的账号（多账号相关）
- `Quote` 与 `Source` 在 0.10.0 将成为 `MessageEvent.quote` 与 `MessageEvent.source` 而不是 `MessageChain[1]` 与 `MessageChain[0]`。`Source 与 Quote 不再是 Element 的子类`
- `RegexGroup`
- 现在传入 MessageChain 作为 quote 对象会报错
- 丰富了 CoolDown 的功能
- 现在 `Ariadne.default_action` 会作用于所有发送方法，所有发送方法都可以传入 action 参数

## 不懂就问
`launart.ExportInterface` 是什么？

## Other
消息处理器有什么大更新吗，更新日志好像没什么体会？除了 `RegexGroup`

**Comment by BlueGlassBlock** [comment]
估计内置消息处理器短期内不会有其他改动，除非剥离到 GraiaX Shortcut

**Comment by BlueGlassBlock** [comment]
launart.ExportInterface 是 Service 的对外接口，例如 PlaywrightBrowser
